plugins:
  - jekyll-sitemap

collections:
  slides:
    output: true
  docs:
    output: true

defaults:
  -
    scope:
      path: "_slides"
    values:
      layout: "majestic"
  -
    scope:
      path: "_docs"
    values:
      layout: "default"
